2025-03-31 06:48:28 - INFO - logger - <module> - Приложение запущено
2025-03-31 06:48:28 - INFO - logger - <module> - Добавляем логирование в остальные файлы проекта...
2025-03-31 06:48:28 - INFO - logger - <module> - Логирование в database.py: все запросы к серверу регистрируются.
2025-03-31 06:48:28 - INFO - logger - <module> - Логирование в COM.py: события работы с COM-портами фиксируются.
2025-03-31 06:48:28 - INFO - logger - <module> - Логирование в detail_work.py: операции с деталями регистрируются.
2025-03-31 06:48:28 - INFO - logger - <module> - Логирование в Error.py и ErrorTest.py: ошибки записываются.
2025-03-31 06:48:28 - INFO - logger - <module> - Логирование в этапах Mark.py, Packing.py, Test.py, Work.py.
2025-03-31 06:48:34 - ERROR - logger - log_error - Ошибка: Ошибка при подключении к серверу: timed out
Traceback (most recent call last):
  File "C:\Users\user\Desktop\RFID-marks\GUI\database.py", line 18, in test_connection
    client_socket.connect((serverip, port))
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
TimeoutError: timed out
2025-03-31 06:48:34 - ERROR - logger - log_error - Ошибка: Ошибка соединения с сервером
NoneType: None
2025-03-31 06:48:39 - INFO - logger - log_event - Пользователь выбрал продолжить без соединения
2025-03-31 06:48:39 - INFO - logger - log_event - Главное окно приложения создано
2025-03-31 06:48:39 - ERROR - logger - log_error - Ошибка: Не найден подходящий COM-порт
NoneType: None
2025-03-31 06:48:39 - ERROR - logger - log_error - Ошибка: SerialManager не передан! COM-порт не будет работать.
NoneType: None
2025-03-31 06:48:39 - INFO - logger - log_event - Создан интерфейс админ-панели
2025-03-31 06:48:39 - INFO - logger - log_event - Enter to mark
2025-03-31 06:48:39 - INFO - logger - log_event - Enter to Test
2025-03-31 06:48:39 - INFO - logger - log_event - Enter to Packing
2025-03-31 06:48:39 - INFO - logger - log_event - Enter to Login page AA
2025-03-31 06:48:39 - INFO - logger - log_event - Enter to assembly
2025-03-31 06:48:39 - INFO - logger - log_event - Enter to mark
2025-03-31 06:48:39 - INFO - logger - log_event - Enter to Test
2025-03-31 06:48:39 - INFO - logger - log_event - Enter to Packing
2025-03-31 06:48:39 - INFO - logger - log_event - Enter to Login page AA
2025-03-31 06:48:39 - INFO - logger - log_event - Enter to assembly
2025-03-31 06:48:39 - INFO - logger - log_event - Enter to mark
2025-03-31 06:48:39 - INFO - logger - log_event - Enter to Test
2025-03-31 06:48:39 - INFO - logger - log_event - Enter to Packing
2025-03-31 06:48:39 - INFO - logger - log_event - Enter to Login page AA
2025-03-31 06:48:39 - INFO - logger - log_event - Enter to assembly
2025-03-31 06:48:39 - INFO - logger - log_event - Enter to mark
2025-03-31 06:48:39 - INFO - logger - log_event - Enter to Test
2025-03-31 06:48:39 - INFO - logger - log_event - Enter to Packing
2025-03-31 06:48:39 - INFO - logger - log_event - Enter to Login page AA
2025-03-31 06:48:39 - INFO - logger - log_event - Enter to assembly
2025-03-31 06:48:39 - INFO - logger - log_event - Enter to mark
2025-03-31 06:48:39 - INFO - logger - log_event - Enter to Test
2025-03-31 06:48:39 - INFO - logger - log_event - Enter to Packing
2025-03-31 06:48:39 - INFO - logger - log_event - Enter to Login page AA
2025-03-31 06:48:39 - INFO - logger - log_event - Enter to assembly
2025-03-31 06:48:41 - INFO - logger - log_event - Попытка аутентификации пользователя с UID: None
2025-03-31 06:48:41 - INFO - logger - log_event - Запрос: {'type': 'user', 'uid': None}
2025-03-31 06:48:42 - ERROR - logger - log_error - Ошибка: Не удалось аутентифицировать пользователя: Степанов Сергей
NoneType: None
2025-03-31 06:48:43 - INFO - logger - log_event - Закрытие приложения button.py
2025-03-31 06:48:43 - INFO - logger - log_application_exit - Приложение завершено
